Full Website Navigation
roodjinocherilus/magicmath pull request #5
Opened 2023-05-14 04:59 UTC by roodjinocherilus

2023-05-14 05:04 UTC, roodjinocherilus commented
In this PR, I have developed a full website with several pages: Home, Calculator, and Quote.

2023-05-14 05:08 UTC, topeogunleye commented
> In this PR, I have developed a full website with several pages: Home, Calculator, and Quote.

@roodjinocherilus, Please kindly click on the three dots on your PR description to paste this description there as that is the proper way of adding a PR description.

2023-05-14 05:14 UTC, topeogunleye reviewed
Hi @roodjinocherilus, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project, that doesn't have a pull request description, kindly add one. See a demo on how to add a PR description below:

![pull_request_desc](https://user-images.githubusercontent.com/52934128/177452738-0610c008-a53a-454e-8aac-635cb4ed812c.gif)
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

2023-05-14 05:53 UTC, topeogunleye requested changes
Hi @roodjinocherilus, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * No linter errors. :heavy_check_mark:
> * Followed Github flow :heavy_check_mark:
> * PR has a good summary :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] thank you for submitting your code for review. I appreciate your effort and creativity in completing the Math magicians: full website milestone. However, I noticed that your branch name is `full`, which is not descriptive enough and does not follow the convention of being named after an action or feature. This convention helps to keep the codebase organized and easy to understand by other developers. It also makes it easier to track the changes and merge the branches without conflicts. A good branch name should be descriptive, concise, and use hyphens to separate words. For example, if you are working on adding a calculator component, you could name your branch `add-calculator` or `feature/calculator`. If you are fixing a bug in the navigation bar, you could name your branch `fix-nav-bar` or `bugfix/nav-bar`. if you finished the full Math Magicians website, you could name your branch `finished-math-magicians-website`

Please try to rename your branch and resubmit your code for review. If you have any questions or need further assistance, feel free to reach out to me. Happy coding! 😊
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-14 05:53 UTC, topeogunleye commented on src/components/Home.js
> +    <div>
- [ ] As required please make sure that you follow the general layout should match the given wireframe.
- [ ] Kindly add the `Math Magicians` logo to the left of the header.
- [ ] Kindly make sure that your Navigation bar is aligned to the right as seen in the given wireframe.
- [ ] The text `Welcome To The Homepage` should be aligned to the left and not centered as seen in the given wireframe
- [ ] Your paragraph on the page should be aligned to the left as seen in the given wireframe.

|   |  |
| ------------- | ------------- |
| Your Design | <img width="917" alt="image" src="https://github.com/roodjinocherilus/magicmath/assets/52934128/88ffcc2d-740e-45fc-ba79-9139b1f9e491">  |
| Given Wireframe  | ![image](https://github.com/roodjinocherilus/magicmath/assets/52934128/f9125fa6-5a72-47e4-9026-f4ca7100fea9)  |

2023-05-14 05:53 UTC, topeogunleye commented on src/App.js
> +          <Route path="/calculator" element={<Calculator />} />
- [ ] There should be a text aligned to the left of the calculator as seen the the given wireframe. The calculator shouldn''t be centered. 
- [ ] The calculator should be aligned to the right and the text besides it aligned to the right of the page.

|   |   |
| ------------- | ------------- |
| Your Design | <img width="916" alt="image" src="https://github.com/roodjinocherilus/magicmath/assets/52934128/c50eb0a9-c8fc-4991-8af4-6f0c1e28313d">  |
| Given Wireframe  | ![image](https://github.com/roodjinocherilus/magicmath/assets/52934128/7b26ebcc-98fb-4164-a4a1-405f20abb3c1)
  |

2023-06-18 04:24 UTC, BenMukebo reviewed
## Hi @roodjinocherilus 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that was not approved in your previous weeks therefore kindly create a new pull request so that it may be count as a first review in you dashboard

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@BenMukebo` so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-18 04:34 UTC, closed without merging